from __future__ import annotations

# One source of truth for currency display, validation and conversion fallback.
# Rates are local-currency units per USD. The baseline snapshot is dated 2026-08-11;
# the optional FX refresh endpoint can update cached rates without making a user request depend on the network.
CURRENCY_CONFIG = {
    'AED': {'name': 'UAE Dirham', 'symbol': 'AED', 'locale': 'en-AE', 'decimalDigits': 2, 'rateToUSD': 3.6725},
    'AFN': {'name': 'AFN', 'symbol': 'AFN', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 65.614},
    'ALL': {'name': 'ALL', 'symbol': 'ALL', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 80.41},
    'AMD': {'name': 'AMD', 'symbol': 'AMD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 365.8},
    'ANG': {'name': 'ANG', 'symbol': 'ANG', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1.79},
    'AOA': {'name': 'AOA', 'symbol': 'AOA', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 917.97},
    'ARS': {'name': 'ARS', 'symbol': 'ARS', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1498.56},
    'AUD': {'name': 'Australian Dollar', 'symbol': 'A$', 'locale': 'en-AU', 'decimalDigits': 2, 'rateToUSD': 1.4171},
    'BGN': {'name': 'Bulgarian Lev', 'symbol': 'BGN', 'locale': 'bg-BG', 'decimalDigits': 2, 'rateToUSD': 2.2610},
    'KPW': {'name': 'North Korean Won', 'symbol': '₩', 'locale': 'ko-KP', 'decimalDigits': 0, 'rateToUSD': 900.0},
    'AWG': {'name': 'AWG', 'symbol': 'AWG', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1.7898},
    'AZN': {'name': 'AZN', 'symbol': 'AZN', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1.6994},
    'BAM': {'name': 'BAM', 'symbol': 'BAM', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1.6918},
    'BBD': {'name': 'BBD', 'symbol': 'BBD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2.0389},
    'BDT': {'name': 'BDT', 'symbol': 'BDT', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 123.59},
    'BHD': {'name': 'BHD', 'symbol': 'BHD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 0.376},
    'BIF': {'name': 'BIF', 'symbol': 'BIF', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 2996.67},
    'BMD': {'name': 'BMD', 'symbol': 'BMD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1.0},
    'BND': {'name': 'BND', 'symbol': 'BND', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1.2799},
    'BOB': {'name': 'BOB', 'symbol': 'BOB', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 11.9263},
    'BRL': {'name': 'Brazilian Real', 'symbol': 'R$', 'locale': 'pt-BR', 'decimalDigits': 2, 'rateToUSD': 5.0951},
    'BSD': {'name': 'BSD', 'symbol': 'BSD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1.0129},
    'BTN': {'name': 'BTN', 'symbol': 'BTN', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 95.31},
    'BWP': {'name': 'BWP', 'symbol': 'BWP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 13.2927},
    'BYN': {'name': 'BYN', 'symbol': 'BYN', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2.9621},
    'BZD': {'name': 'BZD', 'symbol': 'BZD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2.0386},
    'CAD': {'name': 'Canadian Dollar', 'symbol': 'CA$', 'locale': 'en-CA', 'decimalDigits': 2, 'rateToUSD': 1.3937},
    'CDF': {'name': 'CDF', 'symbol': 'CDF', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2268.31},
    'CHF': {'name': 'Swiss Franc', 'symbol': 'CHF', 'locale': 'de-CH', 'decimalDigits': 2, 'rateToUSD': 0.80903},
    'CLP': {'name': 'CLP', 'symbol': 'CLP', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 914.13},
    'CNY': {'name': 'Chinese Yuan', 'symbol': '¥', 'locale': 'zh-CN', 'decimalDigits': 2, 'rateToUSD': 6.7411},
    'COP': {'name': 'COP', 'symbol': 'COP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 3140.68},
    'CRC': {'name': 'CRC', 'symbol': 'CRC', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 451.79},
    'CUP': {'name': 'CUP', 'symbol': 'CUP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 24.0},
    'CVE': {'name': 'CVE', 'symbol': 'CVE', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 95.38},
    'CZK': {'name': 'Czech Koruna', 'symbol': 'CZK', 'locale': 'cs-CZ', 'decimalDigits': 2, 'rateToUSD': 20.999},
    'DJF': {'name': 'DJF', 'symbol': 'DJF', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 176.92},
    'DKK': {'name': 'Danish Krone', 'symbol': 'DKK', 'locale': 'da-DK', 'decimalDigits': 2, 'rateToUSD': 6.4713},
    'DOP': {'name': 'DOP', 'symbol': 'DOP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 59.428},
    'DZD': {'name': 'Algerian Dinar', 'symbol': 'دج', 'locale': 'ar-DZ', 'decimalDigits': 0, 'rateToUSD': 132.9},
    'EGP': {'name': 'EGP', 'symbol': 'EGP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 49.937},
    'ERN': {'name': 'ERN', 'symbol': 'ERN', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 15.3214},
    'ETB': {'name': 'ETB', 'symbol': 'ETB', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 160.28},
    'EUR': {'name': 'Euro', 'symbol': '€', 'locale': 'fr-FR', 'decimalDigits': 2, 'rateToUSD': 0.86503},
    'FJD': {'name': 'FJD', 'symbol': 'FJD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2.2167},
    'FKP': {'name': 'FKP', 'symbol': 'FKP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 0.74056},
    'GBP': {'name': 'British Pound', 'symbol': '£', 'locale': 'en-GB', 'decimalDigits': 2, 'rateToUSD': 0.74056},
    'GEL': {'name': 'GEL', 'symbol': 'GEL', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2.6158},
    'GHS': {'name': 'GHS', 'symbol': 'GHS', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 11.8137},
    'GIP': {'name': 'GIP', 'symbol': 'GIP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 0.75059},
    'GMD': {'name': 'GMD', 'symbol': 'GMD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 72.586},
    'GNF': {'name': 'GNF', 'symbol': 'GNF', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 8765.0},
    'GTQ': {'name': 'GTQ', 'symbol': 'GTQ', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 7.6263},
    'GYD': {'name': 'GYD', 'symbol': 'GYD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 212.42},
    'HKD': {'name': 'Hong Kong Dollar', 'symbol': 'HK$', 'locale': 'en-HK', 'decimalDigits': 2, 'rateToUSD': 7.8523},
    'HNL': {'name': 'HNL', 'symbol': 'HNL', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 26.825},
    'HTG': {'name': 'HTG', 'symbol': 'HTG', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 130.52},
    'HUF': {'name': 'Hungarian Forint', 'symbol': 'HUF', 'locale': 'hu-HU', 'decimalDigits': 0, 'rateToUSD': 315.22},
    'IDR': {'name': 'Indonesian Rupiah', 'symbol': 'Rp', 'locale': 'id-ID', 'decimalDigits': 0, 'rateToUSD': 17801.0},
    'ILS': {'name': 'Israeli New Shekel', 'symbol': '₪', 'locale': 'he-IL', 'decimalDigits': 2, 'rateToUSD': 3.0002},
    'INR': {'name': 'Indian Rupee', 'symbol': '₹', 'locale': 'en-IN', 'decimalDigits': 2, 'rateToUSD': 95.31},
    'IQD': {'name': 'IQD', 'symbol': 'IQD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1309.08},
    'IRR': {'name': 'IRR', 'symbol': 'IRR', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1370390.0},
    'ISK': {'name': 'ISK', 'symbol': 'ISK', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 123.16},
    'JMD': {'name': 'JMD', 'symbol': 'JMD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 156.82},
    'JOD': {'name': 'JOD', 'symbol': 'JOD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 0.709},
    'JPY': {'name': 'Japanese Yen', 'symbol': '¥', 'locale': 'ja-JP', 'decimalDigits': 0, 'rateToUSD': 158.82},
    'KES': {'name': 'KES', 'symbol': 'KES', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 129.19},
    'KGS': {'name': 'KGS', 'symbol': 'KGS', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 87.45},
    'KHR': {'name': 'KHR', 'symbol': 'KHR', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 4054.85},
    'KMF': {'name': 'KMF', 'symbol': 'KMF', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 426.07},
    'KRW': {'name': 'South Korean Won', 'symbol': '₩', 'locale': 'ko-KR', 'decimalDigits': 0, 'rateToUSD': 1415.83},
    'KWD': {'name': 'KWD', 'symbol': 'KWD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 0.30768},
    'KYD': {'name': 'KYD', 'symbol': 'KYD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 0.83719},
    'KZT': {'name': 'KZT', 'symbol': 'KZT', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 466.76},
    'LAK': {'name': 'LAK', 'symbol': 'LAK', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 22477.0},
    'LBP': {'name': 'LBP', 'symbol': 'LBP', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 90039.0},
    'LKR': {'name': 'LKR', 'symbol': 'LKR', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 336.12},
    'LRD': {'name': 'LRD', 'symbol': 'LRD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 181.42},
    'LSL': {'name': 'LSL', 'symbol': 'LSL', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 16.1948},
    'LYD': {'name': 'LYD', 'symbol': 'LYD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 6.3656},
    'MAD': {'name': 'Moroccan Dirham', 'symbol': 'MAD', 'locale': 'fr-MA', 'decimalDigits': 0, 'rateToUSD': 9.3135},
    'MDL': {'name': 'MDL', 'symbol': 'MDL', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 17.3607},
    'MGA': {'name': 'MGA', 'symbol': 'MGA', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 4291.58},
    'MKD': {'name': 'MKD', 'symbol': 'MKD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 53.255},
    'MMK': {'name': 'MMK', 'symbol': 'MMK', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2097.83},
    'MNT': {'name': 'MNT', 'symbol': 'MNT', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 3594.71},
    'MOP': {'name': 'MOP', 'symbol': 'MOP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 8.0879},
    'MRO': {'name': 'MRO', 'symbol': 'MRO', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 39.571},
    'MRU': {'name': 'MRU', 'symbol': 'MRU', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 40.072},
    'MUR': {'name': 'MUR', 'symbol': 'MUR', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 47.062},
    'MVR': {'name': 'MVR', 'symbol': 'MVR', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 15.3792},
    'MWK': {'name': 'MWK', 'symbol': 'MWK', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1737.47},
    'MXN': {'name': 'Mexican Peso', 'symbol': 'MX$', 'locale': 'es-MX', 'decimalDigits': 2, 'rateToUSD': 17.1435},
    'MYR': {'name': 'Malaysian Ringgit', 'symbol': 'RM', 'locale': 'ms-MY', 'decimalDigits': 2, 'rateToUSD': 4.0901},
    'MZN': {'name': 'MZN', 'symbol': 'MZN', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 63.553},
    'NAD': {'name': 'NAD', 'symbol': 'NAD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 16.1836},
    'NGN': {'name': 'NGN', 'symbol': 'NGN', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1361.59},
    'NIO': {'name': 'NIO', 'symbol': 'NIO', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 36.74},
    'NOK': {'name': 'Norwegian Krone', 'symbol': 'NOK', 'locale': 'nb-NO', 'decimalDigits': 2, 'rateToUSD': 9.5007},
    'NPR': {'name': 'NPR', 'symbol': 'NPR', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 152.41},
    'NZD': {'name': 'New Zealand Dollar', 'symbol': 'NZ$', 'locale': 'en-NZ', 'decimalDigits': 2, 'rateToUSD': 1.6988},
    'OMR': {'name': 'OMR', 'symbol': 'OMR', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 0.3845},
    'PAB': {'name': 'PAB', 'symbol': 'PAB', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 0.9997},
    'PEN': {'name': 'PEN', 'symbol': 'PEN', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 3.3765},
    'PGK': {'name': 'PGK', 'symbol': 'PGK', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 4.4029},
    'PHP': {'name': 'Philippine Peso', 'symbol': '₱', 'locale': 'en-PH', 'decimalDigits': 2, 'rateToUSD': 60.943},
    'PKR': {'name': 'PKR', 'symbol': 'PKR', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 278.34},
    'PLN': {'name': 'Polish Zloty', 'symbol': 'PLN', 'locale': 'pl-PL', 'decimalDigits': 2, 'rateToUSD': 3.723},
    'PYG': {'name': 'PYG', 'symbol': 'PYG', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 5949.0},
    'QAR': {'name': 'QAR', 'symbol': 'QAR', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 3.64},
    'RON': {'name': 'Romanian Leu', 'symbol': 'RON', 'locale': 'ro-RO', 'decimalDigits': 2, 'rateToUSD': 4.5388},
    'RSD': {'name': 'RSD', 'symbol': 'RSD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 101.58},
    'RUB': {'name': 'Russian Ruble', 'symbol': '₽', 'locale': 'ru-RU', 'decimalDigits': 2, 'rateToUSD': 82.45},
    'RWF': {'name': 'RWF', 'symbol': 'RWF', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 1470.27},
    'SAR': {'name': 'Saudi Riyal', 'symbol': 'SAR', 'locale': 'en-SA', 'decimalDigits': 2, 'rateToUSD': 3.75},
    'SBD': {'name': 'SBD', 'symbol': 'SBD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 8.0496},
    'SCR': {'name': 'SCR', 'symbol': 'SCR', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 14.2987},
    'SDG': {'name': 'SDG', 'symbol': 'SDG', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 600.05},
    'SEK': {'name': 'Swedish Krona', 'symbol': 'SEK', 'locale': 'sv-SE', 'decimalDigits': 2, 'rateToUSD': 9.4877},
    'SGD': {'name': 'Singapore Dollar', 'symbol': 'S$', 'locale': 'en-SG', 'decimalDigits': 2, 'rateToUSD': 1.2799},
    'SHP': {'name': 'SHP', 'symbol': 'SHP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 0.74056},
    'SLE': {'name': 'SLE', 'symbol': 'SLE', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 24.224},
    'SOS': {'name': 'SOS', 'symbol': 'SOS', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 571.31},
    'SRD': {'name': 'SRD', 'symbol': 'SRD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 37.842},
    'SSP': {'name': 'SSP', 'symbol': 'SSP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 5523.0},
    'STN': {'name': 'STN', 'symbol': 'STN', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 21.245},
    'SVC': {'name': 'SVC', 'symbol': 'SVC', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 8.749},
    'SYP': {'name': 'SYP', 'symbol': 'SYP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 122.01},
    'SZL': {'name': 'SZL', 'symbol': 'SZL', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 16.212},
    'THB': {'name': 'Thai Baht', 'symbol': '฿', 'locale': 'th-TH', 'decimalDigits': 2, 'rateToUSD': 33.034},
    'TJS': {'name': 'TJS', 'symbol': 'TJS', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 9.2354},
    'TMT': {'name': 'TMT', 'symbol': 'TMT', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 3.5},
    'TND': {'name': 'TND', 'symbol': 'TND', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2.9253},
    'TOP': {'name': 'TOP', 'symbol': 'TOP', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2.3616},
    'TRY': {'name': 'Turkish Lira', 'symbol': '₺', 'locale': 'tr-TR', 'decimalDigits': 2, 'rateToUSD': 47.705},
    'TTD': {'name': 'TTD', 'symbol': 'TTD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 6.739},
    'TWD': {'name': 'New Taiwan Dollar', 'symbol': 'NT$', 'locale': 'zh-TW', 'decimalDigits': 2, 'rateToUSD': 32.23},
    'TZS': {'name': 'TZS', 'symbol': 'TZS', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2640.73},
    'UAH': {'name': 'Ukrainian Hryvnia', 'symbol': '₴', 'locale': 'uk-UA', 'decimalDigits': 2, 'rateToUSD': 44.829},
    'UGX': {'name': 'UGX', 'symbol': 'UGX', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 3725.39},
    'USD': {'name': 'US Dollar', 'symbol': '$', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 1.0},
    'UYU': {'name': 'UYU', 'symbol': 'UYU', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 40.245},
    'UZS': {'name': 'UZS', 'symbol': 'UZS', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 11931.0},
    'VES': {'name': 'VES', 'symbol': 'VES', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 757.01},
    'VND': {'name': 'Vietnamese Dong', 'symbol': '₫', 'locale': 'vi-VN', 'decimalDigits': 0, 'rateToUSD': 26115.0},
    'VUV': {'name': 'VUV', 'symbol': 'VUV', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 117.71},
    'WST': {'name': 'WST', 'symbol': 'WST', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2.7122},
    'XAF': {'name': 'XAF', 'symbol': 'XAF', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 567.42},
    'XCD': {'name': 'XCD', 'symbol': 'XCD', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 2.751},
    'XCG': {'name': 'XCG', 'symbol': 'XCG', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 1.7918},
    'XOF': {'name': 'XOF', 'symbol': 'XOF', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 567.42},
    'XPF': {'name': 'XPF', 'symbol': 'XPF', 'locale': 'en-US', 'decimalDigits': 0, 'rateToUSD': 103.28},
    'YER': {'name': 'YER', 'symbol': 'YER', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 238.18},
    'ZAR': {'name': 'South African Rand', 'symbol': 'R', 'locale': 'en-ZA', 'decimalDigits': 2, 'rateToUSD': 16.162},
    'ZMW': {'name': 'ZMW', 'symbol': 'ZMW', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 18.7309},
    'ZWG': {'name': 'ZWG', 'symbol': 'ZWG', 'locale': 'en-US', 'decimalDigits': 2, 'rateToUSD': 26.611},
}

# Product-budget bounds are expressed independently in USD, then converted to
# each selected currency so every currency has its own stored, configurable limits.
BASE_MIN_USD = 150.0
BASE_MAX_USD = 10000.0
FX_SNAPSHOT_DATE = '2026-08-11'


def get_currency(code: str) -> dict:
    code = str(code or 'USD').upper()
    if code not in CURRENCY_CONFIG:
        raise ValueError(f'Unsupported currency: {code}')
    cfg = dict(CURRENCY_CONFIG[code])
    rate = float(cfg['rateToUSD'])
    cfg['minimum'] = round(BASE_MIN_USD * rate)
    cfg['maximum'] = round(BASE_MAX_USD * rate)
    return cfg


def exported_config() -> dict[str, dict]:
    result = {code: get_currency(code) for code in CURRENCY_CONFIG}
    for cfg in result.values():
        cfg['rateSnapshotDate'] = FX_SNAPSHOT_DATE
    return result
